### ISSUE TITLE
Prefer HTTPS to clone from Git

### ISSUE THREAD

**Issue by person666** [RLovelett/swift-aur#10]
Why not use HTTPS for Git cloning instead of `git+http` in the [`PKGBUILD`](https://github.com/RLovelett/swift-aur/blob/2fe8ae3af8a90fafe856a50549d0b126c1f1a1ea/PKGBUILD#L63)?

**Comment by RLovelett** [comment]
No particular reason. Just an oversight on my part.

Thank you for bringing it to my attention.
