### ISSUE TITLE
Add build in chroot to README

### ISSUE THREAD

**Issue by ahti** [RLovelett/swift-aur#3]
Arch packages can be built in a clean Arch chroot, so the system on which the build is done doesn't influence the process.

This can be done by first installing the `devtools` package and then just using `extra-x86_64-build` in the directory containing the `PKGBUILD` to build the package. More about this can be found in the [TU guidelines](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines) (search for `extra-x86_64-build`) and [here](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot#Convenience_Way).

**Comment by RLovelett** [comment]
Thanks for this tip. I've converted my daily build over to this; way better than my old method. Obviously, as you know, it is not completely building yet but I'll see what I can do to resolve that.

Once I do I'll update the README accordingly.

**Comment by RLovelett** [comment]
I added https://github.com/RLovelett/swift-aur/commit/04dfb539a9ee8c438871e369ad20ba16afd535de this morning. In my testing it builds in my local `chroot` environment.

**Comment by RLovelett** [comment]
Resolved by f1c7613ced94a41a85419a790f53991eb5abff72.
