### ISSUE TITLE
Could you please clarify what the license is on this code? 

### ISSUE THREAD

**Issue by person666** [RLovelett/swift-aur#7]

**Comment by RLovelett** [comment]
[I've added the LICENSE.txt file from the Swift repository upstream.](https://github.com/apple/swift/blob/master/LICENSE.txt) See https://github.com/RLovelett/swift-aur/commit/cf2dbcb391bf79821cd0075c5faa40a6cad33667.

That having been said the license was already provided in the [PKGBUILD](https://github.com/RLovelett/swift-aur/blob/cf2dbcb391bf79821cd0075c5faa40a6cad33667/PKGBUILD#L10).
